name: Deploy

on: 
  push:
    branches: [ main ]
    
  repository_dispatch:
    types: [s3-sync]
    
jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile
      - run: yarn build
              
        env:          
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      - run: |          
          git config --global user.email "lougie.quisel@gmail.com"
          git config --global user.name "loq24"
          git config --global credential.helper cache
          git clone https://${{ secrets.API_TOKEN_GITHUB }}@github.com/loq24/private-portfolio
          cp -a /out/. /private-portfolio/
          cd private-portfolio
          git add .
          git commit -m "$(date)"
          git push
        
      - uses: aws-actions/configure-aws-credentials@v2
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1      
      - run: aws s3 sync ./out s3://test-nextjs-bucket
